import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { openGameStore } from './sqlite-store.mjs';
import { assertRankingEligible } from './game-service.ts';
import { initialProgress } from '../src/game/progression.ts';

test('only the linked local test admin has no fatigue; preview ignores the grant', t => {
  const folder = mkdtempSync(join(tmpdir(), 'lumber-test-admin-'));
  const path = join(folder, 'players.sqlite');
  let now = 100_000;
  let store = openGameStore(path, { now: () => now });
  store.createPlayer('alice'); store.createPlayer('bob');
  t.after(() => { try { store.close(); } catch {} rmSync(folder, { recursive: true, force: true }); });
  const db = new DatabaseSync(path);
  db.exec('CREATE TABLE wallet_links (wallet TEXT PRIMARY KEY, player_id TEXT UNIQUE REFERENCES players(id)) STRICT');
  db.prepare('INSERT INTO wallet_links VALUES (?,?)').run('alice-wallet', 'alice');
  db.prepare('UPDATE players SET progress=? WHERE id=?').run(JSON.stringify({ ...initialProgress('ko'), fatigue: 96, recoveryAt: 100_000 }), 'alice');
  db.close();
  assert.throws(() => store.grantLocalTestAdmin('other-wallet'), /PLAYER_NOT_FOUND/);
  assert.equal(store.grantLocalTestAdmin('alice-wallet'), 'alice');
  assert.equal(store.load('alice').provenance, 'local-test');
  assert.throws(() => assertRankingEligible(store.load('alice')), /TEST_PROGRESS_EXCLUDED/);
  assert.equal(store.load('alice').progress.fatigue, 0);
  assert.equal(store.load('alice').progress.recoveryAt, null);
  const hit = (player, requestId) => store.execute(player, { requestId, expectedRevision: 0, command: { type: 'hit' } });
  assert.equal(hit('alice', 'admin-hit').progress.fatigue, 0);
  assert.equal(hit('bob', 'normal-hit').progress.fatigue, 1);
  now += 2_000;
  const boss = store.execute('alice', { requestId: 'admin-boss', expectedRevision: 1, command: { type: 'hitWorldBoss' } });
  assert.equal(boss.progress.fatigue, 0);
  assert.equal(boss.worldBoss.hits, 1);
  now += 4_000;
  const batch = store.execute('alice', { requestId: 'admin-batch', expectedRevision: 2, command: { type: 'hitBatch', count: 2 } });
  assert.equal(batch.progress.fatigue, 0);
  assert.equal(batch.progress.totalHits, 3);
  store.close();
  store = openGameStore(path, { mode: 'preview', now: () => now });
  assert.throws(() => store.grantLocalTestAdmin('alice-wallet'), /LOCAL_ADMIN_ONLY/);
  assert.equal(store.load('alice').provenance, 'local-test');
  now += 2_000;
  const previewHit = store.execute('alice', { requestId: 'preview-hit', expectedRevision: 3, command: { type: 'hit' } });
  assert.equal(previewHit.progress.fatigue, 1);
});
